vich_uploader:
    db_driver: orm

    mappings:
        csv:
            uri_prefix: /csv
            upload_destination: '%kernel.project_dir%/public/csv'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
