###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: bulkcommission-mailhog
      ports:
        - "8001:8025"

    redis:
      image: redis:alpine
      container_name: bulkcommission-redis

    mysql:
      image: mysql:5.7
      container_name: bulkcommission-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=bulkcommissions
        - MYSQL_USER=bulkcommissions
        - MYSQL_PASSWORD=bulkcommissions1234
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: bulkcommission-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: bulkcommission-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

